print('^'*20)
text = "{:^15}".format("연산 프로그램")
print(text)
print('^'*20)
# a=int(input('첫번째 값:'))
# b=int(input('두번째 값:'))
a,b=map(int,input("a, b를 공백을 두고 입력하시오.: ").split())
print(f'{a}+{b}={a+b}')
print(f'{a}-{b}={a-b}')
print(f'{a}*{b}={a*b}')
print(f'{a}/{b}={a/b}')
print(f'{a}**{b}={a**b}')
print(f'{a}//{b}={a//b}')